resources:
  - name: u14_dd_repo
    type: gitRepo
    integration: avinci_gh
    pointer:
      sourceName: dry-dock/u14
      branch: master

  - name: u14_dd_img
    type: image
    integration: shipDH
    pointer:
      sourceName: "drydock/u14"
    seed:
      versionName: master

  - name: u14all_dd_repo
    type: gitRepo
    integration: avinci_gh
    pointer:
      sourceName: dry-dock/u14all
      branch: master

  - name: u14all_dd_img
    type: image
    integration: shipDH
    pointer:
      sourceName: "drydock/u14all"
    seed:
      versionName: master

  - name: u14nodall_dd_repo
    type: gitRepo
    integration: avinci_gh
    pointer:
      sourceName: dry-dock/u14nodall
      branch: master

  - name: u14nodall_dd_img
    type: image
    integration: shipDH
    pointer:
      sourceName: "drydock/u14nodall"
    seed:
      versionName: master

  - name: u14pytall_dd_repo
    type: gitRepo
    integration: avinci_gh
    pointer:
      sourceName: dry-dock/u14pytall
      branch: master

  - name: u14pytall_dd_img
    type: image
    integration: shipDH
    pointer:
      sourceName: "drydock/u14pytall"
    seed:
      versionName: master

  - name: u14javall_dd_repo
    type: gitRepo
    integration: avinci_gh
    pointer:
      sourceName: dry-dock/u14javall
      branch: master

  - name: u14javall_dd_img
    type: image
    integration: shipDH
    pointer:
      sourceName: "drydock/u14javall"
    seed:
      versionName: master

  - name: u14cppall_dd_repo
    type: gitRepo
    integration: avinci_gh
    pointer:
      sourceName: dry-dock/u14cppall
      branch: master

  - name: u14cppall_dd_img
    type: image
    integration: shipDH
    pointer:
      sourceName: "drydock/u14cppall"
    seed:
      versionName: master

  - name: u14ruball_dd_repo
    type: gitRepo
    integration: avinci_gh
    pointer:
      sourceName: dry-dock/u14ruball
      branch: master

  - name: u14ruball_dd_img
    type: image
    integration: shipDH
    pointer:
      sourceName: "drydock/u14ruball"
    seed:
      versionName: master

  - name: u14phpall_dd_repo
    type: gitRepo
    integration: avinci_gh
    pointer:
      sourceName: dry-dock/u14phpall
      branch: master

  - name: u14phpall_dd_img
    type: image
    integration: shipDH
    pointer:
      sourceName: "drydock/u14phpall"
    seed:
      versionName: master

  - name: u14scaall_dd_repo
    type: gitRepo
    integration: avinci_gh
    pointer:
      sourceName: dry-dock/u14scaall
      branch: master

  - name: u14scaall_dd_img
    type: image
    integration: shipDH
    pointer:
      sourceName: "drydock/u14scaall"
    seed:
      versionName: master

  - name: u14cloall_dd_repo
    type: gitRepo
    integration: avinci_gh
    pointer:
      sourceName: dry-dock/u14cloall
      branch: master

  - name: u14cloall_dd_img
    type: image
    integration: shipDH
    pointer:
      sourceName: "drydock/u14cloall"
    seed:
      versionName: master

  - name: u14golall_dd_repo
    type: gitRepo
    integration: avinci_gh
    pointer:
      sourceName: dry-dock/u14golall
      branch: master

  - name: u14golall_dd_img
    type: image
    integration: shipDH
    pointer:
      sourceName: "drydock/u14golall"
    seed:
      versionName: master

jobs:
  - name: u14_x8664_build
    type: runSh
    triggerMode: parallel
    dependencyMode: strict
    runtime:
      nodePool: x86_u1404_dyn_large_01
    steps:
      - IN: u14_dd_repo
      - TASK:
          name: u14_build
          runtime:
            options:
              env:
                - REL_VER: "master"
                - IMG_OUT: "u14_dd_img"
                - RES_REPO: "u14_dd_repo"
          script:
            - REPO_COMMIT=$(shipctl get_resource_version_key "$RES_REPO" "shaData.commitSha")
            - IMG_NAME=$(shipctl get_resource_version_key $IMG_OUT "sourceName")
            - DH_USR_NAME=$(shipctl get_integration_resource_field $IMG_OUT "userName")
            - DH_PASS=$(shipctl get_integration_resource_field $IMG_OUT "password")
            - pushd $(shipctl get_resource_state "$RES_REPO")
            - docker build -t=$IMG_NAME:$REL_VER --pull .
            - docker login -u $DH_USR_NAME -p $DH_PASS
            - docker push $IMG_NAME:$REL_VER
      - OUT: u14_dd_img
    on_success:
      script:
        - shipctl put_resource_state_multi $JOB_NAME "versionName=$REL_VER" "IMG_REPO_COMMIT_SHA=$REPO_COMMIT"
        - shipctl put_resource_state_multi $IMG_OUT "versionName=$REL_VER" "IMG_REPO_COMMIT_SHA=$REPO_COMMIT" "BUILD_NUMBER=$BUILD_NUMBER"

  - name: u14all_x8664_build
    type: runSh
    triggerMode: parallel
    dependencyMode: strict
    runtime:
      nodePool: x86_u1404_dyn_large_01
    steps:
      - IN: u14all_dd_repo
      - IN: u14_dd_img
      - TASK:
          name: u14all_build
          runtime:
            options:
              env:
                - IMG_BASE: "u14_dd_img"
                - IMG_OUT: "u14all_dd_img"
                - RES_REPO: "u14all_dd_repo"
          script:
            - REL_VER=$(shipctl get_resource_version_key "$IMG_BASE" "versionName")
            - REPO_COMMIT=$(shipctl get_resource_version_key "$RES_REPO" "shaData.commitSha")
            - IMG_NAME=$(shipctl get_resource_version_key $IMG_OUT "sourceName")
            - DH_USR_NAME=$(shipctl get_integration_resource_field $IMG_OUT "userName")
            - DH_PASS=$(shipctl get_integration_resource_field $IMG_OUT "password")
            - pushd $(shipctl get_resource_state "$RES_REPO")
            - docker build -t=$IMG_NAME:$REL_VER --pull .
            - docker login -u $DH_USR_NAME -p $DH_PASS
            - docker push $IMG_NAME:$REL_VER
      - OUT: u14all_dd_img
    on_success:
      script:
        - shipctl put_resource_state_multi $JOB_NAME "versionName=$REL_VER" "IMG_REPO_COMMIT_SHA=$REPO_COMMIT"
        - shipctl put_resource_state_multi $IMG_OUT "versionName=$REL_VER" "IMG_REPO_COMMIT_SHA=$REPO_COMMIT" "BUILD_NUMBER=$BUILD_NUMBER"

  - name: u14nodall_x8664_build
    type: runSh
    triggerMode: parallel
    dependencyMode: strict
    runtime:
      nodePool: x86_u1404_dyn_large_01
    steps:
      - IN: u14nodall_dd_repo
      - IN: u14all_dd_img
      - TASK:
          name: u14nodall_build
          runtime:
            options:
              env:
                - IMG_BASE: "u14all_dd_img"
                - IMG_OUT: "u14nodall_dd_img"
                - RES_REPO: "u14nodall_dd_repo"
          script:
            - REL_VER=$(shipctl get_resource_version_key "$IMG_BASE" "versionName")
            - REPO_COMMIT=$(shipctl get_resource_version_key "$RES_REPO" "shaData.commitSha")
            - IMG_NAME=$(shipctl get_resource_version_key $IMG_OUT "sourceName")
            - DH_USR_NAME=$(shipctl get_integration_resource_field $IMG_OUT "userName")
            - DH_PASS=$(shipctl get_integration_resource_field $IMG_OUT "password")
            - pushd $(shipctl get_resource_state "$RES_REPO")
            - docker build -t=$IMG_NAME:$REL_VER --pull .
            - docker login -u $DH_USR_NAME -p $DH_PASS
            - docker push $IMG_NAME:$REL_VER
      - OUT: u14nodall_dd_img
    on_success:
      script:
        - shipctl put_resource_state_multi $JOB_NAME "versionName=$REL_VER" "IMG_REPO_COMMIT_SHA=$REPO_COMMIT"
        - shipctl put_resource_state_multi $IMG_OUT "versionName=$REL_VER" "IMG_REPO_COMMIT_SHA=$REPO_COMMIT" "BUILD_NUMBER=$BUILD_NUMBER"

  - name: u14pytall_x8664_build
    type: runSh
    triggerMode: parallel
    dependencyMode: strict
    runtime:
      nodePool: x86_u1404_dyn_large_01
    steps:
      - IN: u14pytall_dd_repo
      - IN: u14all_dd_img
      - TASK:
          name: u14pytall_build
          runtime:
            options:
              env:
                - IMG_BASE: "u14all_dd_img"
                - IMG_OUT: "u14pytall_dd_img"
                - RES_REPO: "u14pytall_dd_repo"
          script:
            - REL_VER=$(shipctl get_resource_version_key "$IMG_BASE" "versionName")
            - REPO_COMMIT=$(shipctl get_resource_version_key "$RES_REPO" "shaData.commitSha")
            - IMG_NAME=$(shipctl get_resource_version_key $IMG_OUT "sourceName")
            - DH_USR_NAME=$(shipctl get_integration_resource_field $IMG_OUT "userName")
            - DH_PASS=$(shipctl get_integration_resource_field $IMG_OUT "password")
            - pushd $(shipctl get_resource_state "$RES_REPO")
            - docker build -t=$IMG_NAME:$REL_VER --pull .
            - docker login -u $DH_USR_NAME -p $DH_PASS
            - docker push $IMG_NAME:$REL_VER
      - OUT: u14pytall_dd_img
    on_success:
      script:
        - shipctl put_resource_state_multi $JOB_NAME "versionName=$REL_VER" "IMG_REPO_COMMIT_SHA=$REPO_COMMIT"
        - shipctl put_resource_state_multi $IMG_OUT "versionName=$REL_VER" "IMG_REPO_COMMIT_SHA=$REPO_COMMIT" "BUILD_NUMBER=$BUILD_NUMBER"

  - name: u14javall_x8664_build
    type: runSh
    triggerMode: parallel
    dependencyMode: strict
    runtime:
      nodePool: x86_u1404_dyn_large_01
    steps:
      - IN: u14javall_dd_repo
      - IN: u14all_dd_img
      - TASK:
          name: u14pytall_build
          runtime:
            options:
              env:
                - IMG_BASE: "u14all_dd_img"
                - IMG_OUT: "u14javall_dd_img"
                - RES_REPO: "u14javall_dd_repo"
          script:
            - REL_VER=$(shipctl get_resource_version_key "$IMG_BASE" "versionName")
            - REPO_COMMIT=$(shipctl get_resource_version_key "$RES_REPO" "shaData.commitSha")
            - IMG_NAME=$(shipctl get_resource_version_key $IMG_OUT "sourceName")
            - DH_USR_NAME=$(shipctl get_integration_resource_field $IMG_OUT "userName")
            - DH_PASS=$(shipctl get_integration_resource_field $IMG_OUT "password")
            - pushd $(shipctl get_resource_state "$RES_REPO")
            - docker build -t=$IMG_NAME:$REL_VER --pull .
            - docker login -u $DH_USR_NAME -p $DH_PASS
            - docker push $IMG_NAME:$REL_VER
      - OUT: u14javall_dd_img
    on_success:
      script:
        - shipctl put_resource_state_multi $JOB_NAME "versionName=$REL_VER" "IMG_REPO_COMMIT_SHA=$REPO_COMMIT"
        - shipctl put_resource_state_multi $IMG_OUT "versionName=$REL_VER" "IMG_REPO_COMMIT_SHA=$REPO_COMMIT" "BUILD_NUMBER=$BUILD_NUMBER"

  - name: u14cppall_x8664_build
    type: runSh
    triggerMode: parallel
    dependencyMode: strict
    runtime:
      nodePool: x86_u1404_dyn_large_01
    steps:
      - IN: u14cppall_dd_repo
      - IN: u14all_dd_img
      - TASK:
          name: u14cppall_build
          runtime:
            options:
              env:
                - IMG_BASE: "u14all_dd_img"
                - IMG_OUT: "u14cppall_dd_img"
                - RES_REPO: "u14cppall_dd_repo"
          script:
            - REL_VER=$(shipctl get_resource_version_key "$IMG_BASE" "versionName")
            - REPO_COMMIT=$(shipctl get_resource_version_key "$RES_REPO" "shaData.commitSha")
            - IMG_NAME=$(shipctl get_resource_version_key $IMG_OUT "sourceName")
            - DH_USR_NAME=$(shipctl get_integration_resource_field $IMG_OUT "userName")
            - DH_PASS=$(shipctl get_integration_resource_field $IMG_OUT "password")
            - pushd $(shipctl get_resource_state "$RES_REPO")
            - docker build -t=$IMG_NAME:$REL_VER --pull .
            - docker login -u $DH_USR_NAME -p $DH_PASS
            - docker push $IMG_NAME:$REL_VER
      - OUT: u14cppall_dd_img
    on_success:
      script:
        - shipctl put_resource_state_multi $JOB_NAME "versionName=$REL_VER" "IMG_REPO_COMMIT_SHA=$REPO_COMMIT"
        - shipctl put_resource_state_multi $IMG_OUT "versionName=$REL_VER" "IMG_REPO_COMMIT_SHA=$REPO_COMMIT" "BUILD_NUMBER=$BUILD_NUMBER"

  - name: u14golall_x8664_build
    type: runSh
    triggerMode: parallel
    dependencyMode: strict
    runtime:
      nodePool: x86_u1404_dyn_large_01
    steps:
      - IN: u14golall_dd_repo
      - IN: u14all_dd_img
      - TASK:
          name: u14golall_build
          runtime:
            options:
              env:
                - IMG_BASE: "u14all_dd_img"
                - IMG_OUT: "u14golall_dd_img"
                - RES_REPO: "u14golall_dd_repo"
          script:
            - REL_VER=$(shipctl get_resource_version_key "$IMG_BASE" "versionName")
            - REPO_COMMIT=$(shipctl get_resource_version_key "$RES_REPO" "shaData.commitSha")
            - IMG_NAME=$(shipctl get_resource_version_key $IMG_OUT "sourceName")
            - DH_USR_NAME=$(shipctl get_integration_resource_field $IMG_OUT "userName")
            - DH_PASS=$(shipctl get_integration_resource_field $IMG_OUT "password")
            - pushd $(shipctl get_resource_state "$RES_REPO")
            - docker build -t=$IMG_NAME:$REL_VER --pull .
            - docker login -u $DH_USR_NAME -p $DH_PASS
            - docker push $IMG_NAME:$REL_VER
      - OUT: u14golall_dd_img
    on_success:
      script:
        - shipctl put_resource_state_multi $JOB_NAME "versionName=$REL_VER" "IMG_REPO_COMMIT_SHA=$REPO_COMMIT"
        - shipctl put_resource_state_multi $IMG_OUT "versionName=$REL_VER" "IMG_REPO_COMMIT_SHA=$REPO_COMMIT" "BUILD_NUMBER=$BUILD_NUMBER"

  - name: u14phpall_x8664_build
    type: runSh
    triggerMode: parallel
    dependencyMode: strict
    runtime:
      nodePool: x86_u1404_dyn_large_01
    steps:
      - IN: u14phpall_dd_repo
      - IN: u14all_dd_img
      - TASK:
          name: u14phpall_build
          runtime:
            options:
              env:
                - IMG_BASE: "u14all_dd_img"
                - IMG_OUT: "u14phpall_dd_img"
                - RES_REPO: "u14phpall_dd_repo"
          script:
            - REL_VER=$(shipctl get_resource_version_key "$IMG_BASE" "versionName")
            - REPO_COMMIT=$(shipctl get_resource_version_key "$RES_REPO" "shaData.commitSha")
            - IMG_NAME=$(shipctl get_resource_version_key $IMG_OUT "sourceName")
            - DH_USR_NAME=$(shipctl get_integration_resource_field $IMG_OUT "userName")
            - DH_PASS=$(shipctl get_integration_resource_field $IMG_OUT "password")
            - pushd $(shipctl get_resource_state "$RES_REPO")
            - docker build -t=$IMG_NAME:$REL_VER --pull .
            - docker login -u $DH_USR_NAME -p $DH_PASS
            - docker push $IMG_NAME:$REL_VER
      - OUT: u14phpall_dd_img
    on_success:
      script:
        - shipctl put_resource_state_multi $JOB_NAME "versionName=$REL_VER" "IMG_REPO_COMMIT_SHA=$REPO_COMMIT"
        - shipctl put_resource_state_multi $IMG_OUT "versionName=$REL_VER" "IMG_REPO_COMMIT_SHA=$REPO_COMMIT" "BUILD_NUMBER=$BUILD_NUMBER"

  - name: u14cloall_x8664_build
    type: runSh
    triggerMode: parallel
    dependencyMode: strict
    runtime:
      nodePool: x86_u1404_dyn_large_01
    steps:
      - IN: u14cloall_dd_repo
      - IN: u14all_dd_img
      - TASK:
          name: u14cloall_build
          runtime:
            options:
              env:
                - IMG_BASE: "u14all_dd_img"
                - IMG_OUT: "u14cloall_dd_img"
                - RES_REPO: "u14cloall_dd_repo"
          script:
            - REL_VER=$(shipctl get_resource_version_key "$IMG_BASE" "versionName")
            - REPO_COMMIT=$(shipctl get_resource_version_key "$RES_REPO" "shaData.commitSha")
            - IMG_NAME=$(shipctl get_resource_version_key $IMG_OUT "sourceName")
            - DH_USR_NAME=$(shipctl get_integration_resource_field $IMG_OUT "userName")
            - DH_PASS=$(shipctl get_integration_resource_field $IMG_OUT "password")
            - pushd $(shipctl get_resource_state "$RES_REPO")
            - docker build -t=$IMG_NAME:$REL_VER --pull .
            - docker login -u $DH_USR_NAME -p $DH_PASS
            - docker push $IMG_NAME:$REL_VER
      - OUT: u14cloall_dd_img
    on_success:
      script:
        - shipctl put_resource_state_multi $JOB_NAME "versionName=$REL_VER" "IMG_REPO_COMMIT_SHA=$REPO_COMMIT"
        - shipctl put_resource_state_multi $IMG_OUT "versionName=$REL_VER" "IMG_REPO_COMMIT_SHA=$REPO_COMMIT" "BUILD_NUMBER=$BUILD_NUMBER"

  - name: u14ruball_x8664_build
    type: runSh
    triggerMode: parallel
    dependencyMode: strict
    runtime:
      nodePool: x86_u1404_dyn_large_01
    steps:
      - IN: u14ruball_dd_repo
      - IN: u14all_dd_img
      - TASK:
          name: u14ruball_build
          runtime:
            options:
              env:
                - IMG_BASE: "u14all_dd_img"
                - IMG_OUT: "u14ruball_dd_img"
                - RES_REPO: "u14ruball_dd_repo"
          script:
            - REL_VER=$(shipctl get_resource_version_key "$IMG_BASE" "versionName")
            - REPO_COMMIT=$(shipctl get_resource_version_key "$RES_REPO" "shaData.commitSha")
            - IMG_NAME=$(shipctl get_resource_version_key $IMG_OUT "sourceName")
            - DH_USR_NAME=$(shipctl get_integration_resource_field $IMG_OUT "userName")
            - DH_PASS=$(shipctl get_integration_resource_field $IMG_OUT "password")
            - pushd $(shipctl get_resource_state "$RES_REPO")
            - docker build -t=$IMG_NAME:$REL_VER --pull .
            - docker login -u $DH_USR_NAME -p $DH_PASS
            - docker push $IMG_NAME:$REL_VER
      - OUT: u14ruball_dd_img
    on_success:
      script:
        - shipctl put_resource_state_multi $JOB_NAME "versionName=$REL_VER" "IMG_REPO_COMMIT_SHA=$REPO_COMMIT"
        - shipctl put_resource_state_multi $IMG_OUT "versionName=$REL_VER" "IMG_REPO_COMMIT_SHA=$REPO_COMMIT" "BUILD_NUMBER=$BUILD_NUMBER"

  - name: u14scaall_x8664_build
    type: runSh
    triggerMode: parallel
    dependencyMode: strict
    runtime:
      nodePool: x86_u1404_dyn_large_01
    steps:
      - IN: u14scaall_dd_repo
      - IN: u14javall_dd_img
      - TASK:
          name: u14scaall_build
          runtime:
            options:
              env:
                - IMG_BASE: "u14javall_dd_img"
                - IMG_OUT: "u14scaall_dd_img"
                - RES_REPO: "u14scaall_dd_repo"
          script:
            - REL_VER=$(shipctl get_resource_version_key "$IMG_BASE" "versionName")
            - REPO_COMMIT=$(shipctl get_resource_version_key "$RES_REPO" "shaData.commitSha")
            - IMG_NAME=$(shipctl get_resource_version_key $IMG_OUT "sourceName")
            - DH_USR_NAME=$(shipctl get_integration_resource_field $IMG_OUT "userName")
            - DH_PASS=$(shipctl get_integration_resource_field $IMG_OUT "password")
            - pushd $(shipctl get_resource_state "$RES_REPO")
            - docker build -t=$IMG_NAME:$REL_VER --pull .
            - docker login -u $DH_USR_NAME -p $DH_PASS
            - docker push $IMG_NAME:$REL_VER
      - OUT: u14scaall_dd_img
    on_success:
      script:
        - shipctl put_resource_state_multi $JOB_NAME "versionName=$REL_VER" "IMG_REPO_COMMIT_SHA=$REPO_COMMIT"
        - shipctl put_resource_state_multi $IMG_OUT "versionName=$REL_VER" "IMG_REPO_COMMIT_SHA=$REPO_COMMIT" "BUILD_NUMBER=$BUILD_NUMBER"
