resources:
  - name: ami_bits_access_cli
    type: cliConfig
    integration: aws_bits_access
    pointer:
      region: us-east-1

  - name: ami_bits_access
    type: integration
    integration: aws_bits_access

  - name: ami_prod_access
    type: integration
    integration: aws_prod_access

jobs:
  - name: baseami_prep
    type: runSh
    triggerMode: parallel
    dependencyMode: strict
    steps:
      - IN: bldami_repo
        switch: off
      - IN: ami_bits_access_cli
        switch: off
      - IN: baseami_params
        switch: off
      - IN: u16cppall_img
      - IN: u16phpall_img
      - IN: u16ruball_img
      - IN: u16scaall_img
      - IN: u16javall_img
      - IN: u16golall_img
      - IN: u16cloall_img
      - IN: u16pytall_img
      - IN: u16nodall_img
      - IN: u14nodall_img
      - IN: u14pytall_img
      - IN: u14cloall_img
      - IN: u14golall_img
      - IN: u14javall_img
      - IN: u14scaall_img
      - IN: u14ruball_img
      - IN: u14phpall_img
      - IN: u14cppall_img
      - IN: node_repo
      - IN: build_reqProc_x86_64_Ubuntu_16_04
      - IN: reqKick_repo
      - IN: cexec_repo
      - TASK:
          script:
            - pushd $(shipctl get_resource_state "bldami_repo")
            - cd base
            - ./basePack.sh baseami_prep ami_bits_access_cli
            - popd
    on_failure:
      - script: cat IN/bldami_repo/gitRepo/base/output.txt #TODO change to standard syntax

  - name: baseami_patch
    type: runSh
    triggerMode: parallel
    dependencyMode: strict
    steps:
      - IN: bldami_repo
        switch: off
      - IN: ami_bits_access_cli
        switch: off
      - IN: baseami_params
        switch: off
      - IN: cexec_repo
      - IN: node_repo
      - IN: build_reqProc_x86_64_Ubuntu_16_04
      - IN: reqKick_repo
      - IN: baseami_prep
      - TASK:
          script:
            - pushd $(shipctl get_resource_state "bldami_repo")
            - cd basePatch
            - ./basePatchPack.sh baseami_patch ami_bits_access_cli baseami_prep
            - popd
    on_failure:
      - script: cat IN/bldami_repo/gitRepo/basePatch/output.txt #TODO change to standard syntax

  - name: finalami_prep
    type: runSh
    triggerMode: parallel
    dependencyMode: strict
    steps:
      - IN: bldami_repo
        switch: off
      - IN: baseami_patch
        switch: off
      - IN: rel_prod
        switch: off
      - IN: baseami_params
        switch: off
      - IN: ami_bits_access
        switch: off
      - IN: dry_dh_x86_64_Ubuntu_tag_push
      - IN: tag_push_img_genexec
      - IN: gh_ship_repos_tag_push
      - TASK:
          script:
            - pushd $(shipctl get_resource_state "bldami_repo")
            - cd exec
            - ./execPack.sh finalami_prep rel_prod baseami_patch ami_bits_access
            - popd
    on_failure:
      - script: cat /build/IN/bldami_repo/gitRepo/exec/output.txt

  - name: baseadmiralami_prep
    type: runSh
    triggerMode: parallel
    dependencyMode: strict
    steps:
      - IN: bldami_repo
        switch: off
      - IN: ami_bits_access
        switch: off
      - IN: ami_prod_access
        switch: off
      - IN: admiralami_params
        switch: off
      - TASK:
          script:
            - pushd $(shipctl get_resource_state "bldami_repo")
            - cd admiral
            - ./admiralPack.sh baseadmiralami_prep ami_bits_access ami_prod_access
            - popd
    on_failure:
      - script: echo 'failed'
      - NOTIFY: slack_rc

  - name: finaladmiralami_prep
    type: runSh
    dependencyMode: strict
    triggerMode: parallel
    steps:
      - IN: bldami_repo
        switch: off
      - IN: baseadmiralami_prep
        switch: off
      - IN: ami_bits_access
        switch: off
      - IN: ami_prod_access
        switch: off
      - IN: rel_prod
        switch: off
      - IN: admiralami_params
        switch: off
      - IN: tag_push_img_genexec
      - IN: gh_ship_repos_tag_push
      - IN: ship_ecr_x86_64_Ubuntu_tag_push
      - TASK:
          script:
            - pushd $(shipctl get_resource_state "bldami_repo")
            - cd admiralPatch
            - ./admiralPatchPack.sh finaladmiralami_prep baseadmiralami_prep rel_prod ami_bits_access ami_prod_access
            - popd
    on_success:
      - script: echo 'SUCCESS'
    on_failure:
      - script: cat /build/IN/bldami_repo/gitRepo/admiralPatch/output.txt

  - name: v532_update
    type: runSh
    dependencyMode: strict
    triggerMode: parallel
    steps:
      - IN: bldami_repo
        switch: off
      - IN: rel_prod
        switch: off
      - IN: baseami_params
        switch: off
      - IN: ami_bits_access
        switch: off
      - IN: tag_push_img_genexec
      - IN: gh_ship_repos_tag_push
      - TASK:
          script:
            - pushd $(shipctl get_resource_state "bldami_repo")
            - cd exec
            - ./execPackTmp.sh v532_update rel_prod ami-3b972d2d v532 Ubuntu_14.04_Docker_1.13.sh true ami_bits_access
            - popd
    on_failure:
      - script: cat /build/IN/bldami_repo/gitRepo/exec/output.txt

  - name: v541_update
    type: runSh
    dependencyMode: strict
    triggerMode: parallel
    steps:
      - IN: bldami_repo
        switch: off
      - IN: rel_prod
        switch: off
      - IN: baseami_params
        switch: off
      - IN: ami_bits_access
        switch: off
      - IN: tag_push_img_genexec
      - IN: gh_ship_repos_tag_push
      - TASK:
          script:
            - pushd $(shipctl get_resource_state "bldami_repo")
            - cd exec
            - ./execPackTmp.sh v541_update rel_prod ami-90813b86 v541 Ubuntu_14.04_Docker_1.13.sh true ami_bits_access
            - popd
    on_failure:
      - script: cat /build/IN/bldami_repo/gitRepo/exec/output.txt

  - name: v551_update
    type: runSh
    dependencyMode: strict
    triggerMode: parallel
    steps:
      - IN: bldami_repo
        switch: off
      - IN: rel_prod
        switch: off
      - IN: baseami_params
        switch: off
      - IN: ami_bits_access
        switch: off
      - IN: tag_push_img_genexec
      - IN: gh_ship_repos_tag_push
      - TASK:
          script:
            - pushd $(shipctl get_resource_state "bldami_repo")
            - cd exec
            - ./execPackTmp.sh v551_update rel_prod ami-4b36535d v551 Ubuntu_14.04_Docker_1.13.sh true ami_bits_access
            - popd
    on_failure:
      - script: cat /build/IN/bldami_repo/gitRepo/exec/output.txt

  - name: v561_update
    type: runSh
    dependencyMode: strict
    triggerMode: parallel
    steps:
      - IN: bldami_repo
        switch: off
      - IN: rel_prod
        switch: off
      - IN: baseami_params
        switch: off
      - IN: ami_bits_access
        switch: off
      - IN: tag_push_img_genexec
      - IN: gh_ship_repos_tag_push
      - TASK:
          script:
            - pushd $(shipctl get_resource_state "bldami_repo")
            - cd exec
            - ./execPackTmp.sh v561_update rel_prod ami-c0a5f5d6 v561 Ubuntu_14.04_Docker_1.13.sh true ami_bits_access
            - popd
    on_failure:
      - script: cat /build/IN/bldami_repo/gitRepo/exec/output.txt

  - name: v573_update
    type: runSh
    dependencyMode: strict
    triggerMode: parallel
    steps:
      - IN: bldami_repo
        switch: off
      - IN: rel_prod
        switch: off
      - IN: baseami_params
        switch: off
      - IN: ami_bits_access
        switch: off
      - IN: tag_push_img_genexec
      - IN: gh_ship_repos_tag_push
      - TASK:
          script:
            - pushd $(shipctl get_resource_state "bldami_repo")
            - cd exec
            - ./execPackTmp.sh v573_update rel_prod ami-b9cfdeaf v573 Ubuntu_14.04_Docker_1.13.sh true ami_bits_access
            - popd
    on_failure:
      - script: cat /build/IN/bldami_repo/gitRepo/exec/output.txt

  - name: v582_update
    type: runSh
    dependencyMode: strict
    triggerMode: parallel
    steps:
      - IN: bldami_repo
        switch: off
      - IN: rel_prod
        switch: off
      - IN: baseami_params
        switch: off
      - IN: ami_bits_access
        switch: off
      - IN: tag_push_img_genexec
      - IN: gh_ship_repos_tag_push
      - TASK:
          script:
            - pushd $(shipctl get_resource_state "bldami_repo")
            - cd exec
            - ./execPackTmp.sh v582_update rel_prod ami-f9d6e782 v582 Ubuntu_14.04_Docker_17.06.sh true ami_bits_access
            - popd
    on_failure:
      - script: cat /build/IN/bldami_repo/gitRepo/exec/output.txt

  - name: v5104_update
    type: runSh
    dependencyMode: strict
    triggerMode: parallel
    steps:
      - IN: bldami_repo
        switch: off
      - IN: rel_prod
        switch: off
      - IN: baseami_params
        switch: off
      - IN: ami_bits_access
        switch: off
      - IN: tag_push_img_genexec
      - IN: gh_ship_repos_tag_push
      - TASK:
          script:
            - pushd $(shipctl get_resource_state "bldami_repo")
            - cd exec
            - ./execPackTmp.sh v5104_update rel_prod ami-312b8d4b v5104 Ubuntu_14.04_Docker_17.06.sh true ami_bits_access
            - popd
    on_failure:
      - script: cat /build/IN/bldami_repo/gitRepo/exec/output.txt

  - name: stable_update
    type: runSh
    dependencyMode: strict
    triggerMode: parallel
    steps:
      - IN: bldami_repo
        switch: off
      - IN: rel_prod
        switch: off
      - IN: baseami_params
        switch: off
      - IN: ami_bits_access
        switch: off
      - IN: tag_push_img_genexec
      - IN: gh_ship_repos_tag_push
      - TASK:
          script:
            - pushd $(shipctl get_resource_state "bldami_repo")
            - cd exec
            - ./execPackTmp.sh stable_update rel_prod ami-4ae41a5c stable Ubuntu_14.04_Docker_1.9.sh false ami_bits_access
            - popd
    on_failure:
      - script: cat /build/IN/bldami_repo/gitRepo/exec/output.txt

  - name: unstable_update
    type: runSh
    dependencyMode: strict
    triggerMode: parallel
    steps:
      - IN: bldami_repo
        switch: off
      - IN: rel_prod
        switch: off
      - IN: baseami_params
        switch: off
      - IN: ami_bits_access
        switch: off
      - IN: tag_push_img_genexec
      - IN: gh_ship_repos_tag_push
      - TASK:
          script:
            - pushd $(shipctl get_resource_state "bldami_repo")
            - cd exec
            - ./execPackTmp.sh unstable_update rel_prod ami-90fd0286 unstable Ubuntu_14.04_Docker_1.11.sh false ami_bits_access
            - popd
    on_failure:
      - script: cat /build/IN/bldami_repo/gitRepo/exec/output.txt
