resources:
  - name: u16_aarch32_dd_repo
    type: gitRepo
    integration: avinci_gh
    pointer:
      sourceName: "dry-dock/aarch32_u16"
      branch: master

  - name: u16_aarch32_dd_img
    type: image
    integration: shipDH
    pointer:
      sourceName: "drydock/aarch32_u16"
    seed:
      versionName: master

jobs:
  - name: u16_aarch32_build
    type: runSh
    triggerMode: parallel
    dependencyMode: strict
    runtime:
      nodePool: aarch32_u1604_cus_01
      container: false
    steps:
      - IN: u16_aarch32_dd_repo
      - TASK:
          name: u16_build
          runtime:
            options:
              env:
                - REL_VER: "master"
                - IMG_OUT: "u16_aarch32_dd_img"
                - RES_REPO: "u16_aarch32_dd_repo"
          script:
            - REPO_COMMIT=$(shipctl get_resource_version_key "$RES_REPO" "shaData.commitSha")
            - IMG_NAME=$(shipctl get_resource_version_key $IMG_OUT "sourceName")
            - DH_USR_NAME=$(shipctl get_integration_resource_field $IMG_OUT "userName")
            - DH_PASS=$(shipctl get_integration_resource_field $IMG_OUT "password")
            - pushd $(shipctl get_resource_state "$RES_REPO")
            - sudo docker build -t=$IMG_NAME:$REL_VER --pull .
            - sudo docker login -u $DH_USR_NAME -p $DH_PASS
            - sudo docker push $IMG_NAME:$REL_VER
      - OUT: u16_aarch32_dd_img
    on_success:
      script:
        - shipctl put_resource_state_multi $JOB_NAME "versionName=$REL_VER" "IMG_REPO_COMMIT_SHA=$REPO_COMMIT"
        - shipctl put_resource_state_multi $IMG_OUT "versionName=$REL_VER" "IMG_REPO_COMMIT_SHA=$REPO_COMMIT" "BUILD_NUMBER=$BUILD_NUMBER"
