resources:
  - name: u16_dd_repo
    type: gitRepo
    integration: avinci_gh
    pointer:
      sourceName: dry-dock/u16
      branch: master

  - name: u16_dd_img
    type: image
    integration: shipDH
    pointer:
      sourceName: "drydock/u16"
    seed:
      versionName: master

  - name: u16all_dd_repo
    type: gitRepo
    integration: avinci_gh
    pointer:
      sourceName: dry-dock/u16all
      branch: master

  - name: u16all_dd_img
    type: image
    integration: shipDH
    pointer:
      sourceName: "drydock/u16all"
    seed:
      versionName: master

  - name: u16nodall_dd_repo
    type: gitRepo
    integration: avinci_gh
    pointer:
      sourceName: dry-dock/u16nodall
      branch: master

  - name: u16nodall_dd_img
    type: image
    integration: shipDH
    pointer:
      sourceName: "drydock/u16nodall"
    seed:
      versionName: master

  - name: u16pytall_dd_repo
    type: gitRepo
    integration: avinci_gh
    pointer:
      sourceName: dry-dock/u16pytall
      branch: master

  - name: u16pytall_dd_img
    type: image
    integration: shipDH
    pointer:
      sourceName: "drydock/u16pytall"
    seed:
      versionName: master

  - name: u16javall_dd_repo
    type: gitRepo
    integration: avinci_gh
    pointer:
      sourceName: dry-dock/u16javall
      branch: master

  - name: u16javall_dd_img
    type: image
    integration: shipDH
    pointer:
      sourceName: "drydock/u16javall"
    seed:
      versionName: master

  - name: u16cppall_dd_repo
    type: gitRepo
    integration: avinci_gh
    pointer:
      sourceName: dry-dock/u16cppall
      branch: master

  - name: u16cppall_dd_img
    type: image
    integration: shipDH
    pointer:
      sourceName: "drydock/u16cppall"
    seed:
      versionName: master

  - name: u16ruball_dd_repo
    type: gitRepo
    integration: avinci_gh
    pointer:
      sourceName: dry-dock/u16ruball
      branch: master

  - name: u16ruball_dd_img
    type: image
    integration: shipDH
    pointer:
      sourceName: "drydock/u16ruball"
    seed:
      versionName: master

  - name: u16phpall_dd_repo
    type: gitRepo
    integration: avinci_gh
    pointer:
      sourceName: dry-dock/u16phpall
      branch: master

  - name: u16phpall_dd_img
    type: image
    integration: shipDH
    pointer:
      sourceName: "drydock/u16phpall"
    seed:
      versionName: master

  - name: u16scaall_dd_repo
    type: gitRepo
    integration: avinci_gh
    pointer:
      sourceName: dry-dock/u16scaall
      branch: master

  - name: u16scaall_dd_img
    type: image
    integration: shipDH
    pointer:
      sourceName: "drydock/u16scaall"
    seed:
      versionName: master

  - name: u16cloall_dd_repo
    type: gitRepo
    integration: avinci_gh
    pointer:
      sourceName: dry-dock/u16cloall
      branch: master

  - name: u16cloall_dd_img
    type: image
    integration: shipDH
    pointer:
      sourceName: "drydock/u16cloall"
    seed:
      versionName: master

  - name: u16golall_dd_repo
    type: gitRepo
    integration: avinci_gh
    pointer:
      sourceName: dry-dock/u16golall
      branch: master

  - name: u16golall_dd_img
    type: image
    integration: shipDH
    pointer:
      sourceName: "drydock/u16golall"
    seed:
      versionName: master

jobs:
  - name: u16_x8664_build
    type: runSh
    triggerMode: parallel
    dependencyMode: strict
    steps:
      - IN: u16_dd_repo
      - TASK:
          name: u16_build
          runtime:
            options:
              env:
                - REL_VER: "master"
                - IMG_OUT: "u16_dd_img"
                - RES_REPO: "u16_dd_repo"
          script:
            - pushd $(shipctl get_resource_state "$RES_REPO")
            - REPO_COMMIT=$(shipctl get_resource_version_key "$RES_REPO" "shaData.commitSha")
            - export IMG_NAME=$(shipctl get_resource_version_key $IMG_OUT "sourceName")
            - export DH_USR_NAME=$(shipctl get_integration_resource_field $IMG_OUT "userName")
            - export DH_PASS=$(shipctl get_integration_resource_field $IMG_OUT "password")
            - sudo docker build -t=$IMG_NAME:$REL_VER --pull .
            - sudo docker login -u $DH_USR_NAME -p $DH_PASS
            - sudo docker push $IMG_NAME:$REL_VER
      - OUT: u16_dd_img
    on_success:
      script:
        - shipctl put_resource_state_multi $JOB_NAME "versionName=$REL_VER" "IMG_REPO_COMMIT_SHA=$REPO_COMMIT"
        - shipctl put_resource_state_multi $IMG_OUT "versionName=$REL_VER" "IMG_REPO_COMMIT_SHA=$REPO_COMMIT" "BUILD_NUMBER=$BUILD_NUMBER"

  - name: u16all_x8664_build
    type: runSh
    triggerMode: parallel
    dependencyMode: strict
    steps:
      - IN: u16all_dd_repo
      - IN: u16_dd_img
      - TASK:
          name: u16all_build
          runtime:
            options:
              env:
                - REL_VER: "master"
                - IMG_OUT: "u16all_dd_img"
                - RES_REPO: "u16all_dd_repo"
          script:
            - pushd $(shipctl get_resource_state "$RES_REPO")
            - REPO_COMMIT=$(shipctl get_resource_version_key "$RES_REPO" "shaData.commitSha")
            - export IMG_NAME=$(shipctl get_resource_version_key $IMG_OUT "sourceName")
            - export DH_USR_NAME=$(shipctl get_integration_resource_field $IMG_OUT "userName")
            - export DH_PASS=$(shipctl get_integration_resource_field $IMG_OUT "password")
            - sudo docker build -t=$IMG_NAME:$REL_VER --pull .
            - sudo docker login -u $DH_USR_NAME -p $DH_PASS
            - sudo docker push $IMG_NAME:$REL_VER
      - OUT: u16all_dd_img
    on_success:
      script:
        - shipctl put_resource_state_multi $JOB_NAME "versionName=$REL_VER" "IMG_REPO_COMMIT_SHA=$REPO_COMMIT"
        - shipctl put_resource_state_multi $IMG_OUT "versionName=$REL_VER" "IMG_REPO_COMMIT_SHA=$REPO_COMMIT" "BUILD_NUMBER=$BUILD_NUMBER"

  - name: u16nodall_x8664_build
    type: runSh
    triggerMode: parallel
    dependencyMode: strict
    steps:
      - IN: u16nodall_dd_repo
      - IN: u16all_dd_img
      - TASK:
          name: u16nodall_build
          runtime:
            options:
              env:
                - REL_VER: "master"
                - IMG_OUT: "u16nodall_dd_img"
                - RES_REPO: "u16nodall_dd_repo"
          script:
            - pushd $(shipctl get_resource_state "$RES_REPO")
            - REPO_COMMIT=$(shipctl get_resource_version_key "$RES_REPO" "shaData.commitSha")
            - export IMG_NAME=$(shipctl get_resource_version_key $IMG_OUT "sourceName")
            - export DH_USR_NAME=$(shipctl get_integration_resource_field $IMG_OUT "userName")
            - export DH_PASS=$(shipctl get_integration_resource_field $IMG_OUT "password")
            - sudo docker build -t=$IMG_NAME:$REL_VER --pull .
            - sudo docker login -u $DH_USR_NAME -p $DH_PASS
            - sudo docker push $IMG_NAME:$REL_VER
      - OUT: u16nodall_dd_img
    on_success:
      script:
        - shipctl put_resource_state_multi $JOB_NAME "versionName=$REL_VER" "IMG_REPO_COMMIT_SHA=$REPO_COMMIT"
        - shipctl put_resource_state_multi $IMG_OUT "versionName=$REL_VER" "IMG_REPO_COMMIT_SHA=$REPO_COMMIT" "BUILD_NUMBER=$BUILD_NUMBER"

  - name: u16pytall_x8664_build
    type: runSh
    triggerMode: parallel
    dependencyMode: strict
    steps:
      - IN: u16pytall_dd_repo
      - IN: u16all_dd_img
      - TASK:
          name: u16pytall_build
          runtime:
            options:
              env:
                - REL_VER: "master"
                - IMG_OUT: "u16pytall_dd_img"
                - RES_REPO: "u16pytall_dd_repo"
          script:
            - pushd $(shipctl get_resource_state "$RES_REPO")
            - REPO_COMMIT=$(shipctl get_resource_version_key "$RES_REPO" "shaData.commitSha")
            - export IMG_NAME=$(shipctl get_resource_version_key $IMG_OUT "sourceName")
            - export DH_USR_NAME=$(shipctl get_integration_resource_field $IMG_OUT "userName")
            - export DH_PASS=$(shipctl get_integration_resource_field $IMG_OUT "password")
            - sudo docker build -t=$IMG_NAME:$REL_VER --pull .
            - sudo docker login -u $DH_USR_NAME -p $DH_PASS
            - sudo docker push $IMG_NAME:$REL_VER
      - OUT: u16pytall_dd_img
    on_success:
      script:
        - shipctl put_resource_state_multi $JOB_NAME "versionName=$REL_VER" "IMG_REPO_COMMIT_SHA=$REPO_COMMIT"
        - shipctl put_resource_state_multi $IMG_OUT "versionName=$REL_VER" "IMG_REPO_COMMIT_SHA=$REPO_COMMIT" "BUILD_NUMBER=$BUILD_NUMBER"

  - name: u16javall_x8664_build
    type: runSh
    triggerMode: parallel
    dependencyMode: strict
    steps:
      - IN: u16javall_dd_repo
      - IN: u16all_dd_img
      - TASK:
          name: u16pytall_build
          runtime:
            options:
              env:
                - REL_VER: "master"
                - IMG_OUT: "u16javall_dd_img"
                - RES_REPO: "u16javall_dd_repo"
          script:
            - pushd $(shipctl get_resource_state "$RES_REPO")
            - REPO_COMMIT=$(shipctl get_resource_version_key "$RES_REPO" "shaData.commitSha")
            - export IMG_NAME=$(shipctl get_resource_version_key $IMG_OUT "sourceName")
            - export DH_USR_NAME=$(shipctl get_integration_resource_field $IMG_OUT "userName")
            - export DH_PASS=$(shipctl get_integration_resource_field $IMG_OUT "password")
            - sudo docker build -t=$IMG_NAME:$REL_VER --pull .
            - sudo docker login -u $DH_USR_NAME -p $DH_PASS
            - sudo docker push $IMG_NAME:$REL_VER
      - OUT: u16javall_dd_img
    on_success:
      script:
        - shipctl put_resource_state_multi $JOB_NAME "versionName=$REL_VER" "IMG_REPO_COMMIT_SHA=$REPO_COMMIT"
        - shipctl put_resource_state_multi $IMG_OUT "versionName=$REL_VER" "IMG_REPO_COMMIT_SHA=$REPO_COMMIT" "BUILD_NUMBER=$BUILD_NUMBER"

  - name: u16cppall_x8664_build
    type: runSh
    triggerMode: parallel
    dependencyMode: strict
    steps:
      - IN: u16cppall_dd_repo
      - IN: u16all_dd_img
      - TASK:
          name: u16cppall_build
          runtime:
            options:
              env:
                - REL_VER: "master"
                - IMG_OUT: "u16cppall_dd_img"
                - RES_REPO: "u16cppall_dd_repo"
          script:
            - pushd $(shipctl get_resource_state "$RES_REPO")
            - REPO_COMMIT=$(shipctl get_resource_version_key "$RES_REPO" "shaData.commitSha")
            - export IMG_NAME=$(shipctl get_resource_version_key $IMG_OUT "sourceName")
            - export DH_USR_NAME=$(shipctl get_integration_resource_field $IMG_OUT "userName")
            - export DH_PASS=$(shipctl get_integration_resource_field $IMG_OUT "password")
            - sudo docker build -t=$IMG_NAME:$REL_VER --pull .
            - sudo docker login -u $DH_USR_NAME -p $DH_PASS
            - sudo docker push $IMG_NAME:$REL_VER
      - OUT: u16cppall_dd_img
    on_success:
      script:
        - shipctl put_resource_state_multi $JOB_NAME "versionName=$REL_VER" "IMG_REPO_COMMIT_SHA=$REPO_COMMIT"
        - shipctl put_resource_state_multi $IMG_OUT "versionName=$REL_VER" "IMG_REPO_COMMIT_SHA=$REPO_COMMIT" "BUILD_NUMBER=$BUILD_NUMBER"

  - name: u16golall_x8664_build
    type: runSh
    triggerMode: parallel
    dependencyMode: strict
    steps:
      - IN: u16golall_dd_repo
      - IN: u16all_dd_img
      - TASK:
          name: u16golall_build
          runtime:
            options:
              env:
                - REL_VER: "master"
                - IMG_OUT: "u16golall_dd_img"
                - RES_REPO: "u16golall_dd_repo"
          script:
            - pushd $(shipctl get_resource_state "$RES_REPO")
            - REPO_COMMIT=$(shipctl get_resource_version_key "$RES_REPO" "shaData.commitSha")
            - export IMG_NAME=$(shipctl get_resource_version_key $IMG_OUT "sourceName")
            - export DH_USR_NAME=$(shipctl get_integration_resource_field $IMG_OUT "userName")
            - export DH_PASS=$(shipctl get_integration_resource_field $IMG_OUT "password")
            - sudo docker build -t=$IMG_NAME:$REL_VER --pull .
            - sudo docker login -u $DH_USR_NAME -p $DH_PASS
            - sudo docker push $IMG_NAME:$REL_VER
      - OUT: u16golall_dd_img
    on_success:
      script:
        - shipctl put_resource_state_multi $JOB_NAME "versionName=$REL_VER" "IMG_REPO_COMMIT_SHA=$REPO_COMMIT"
        - shipctl put_resource_state_multi $IMG_OUT "versionName=$REL_VER" "IMG_REPO_COMMIT_SHA=$REPO_COMMIT" "BUILD_NUMBER=$BUILD_NUMBER"

  - name: u16phpall_x8664_build
    type: runSh
    triggerMode: parallel
    dependencyMode: strict
    steps:
      - IN: u16phpall_dd_repo
      - IN: u16all_dd_img
      - TASK:
          name: u16phpall_build
          runtime:
            options:
              env:
                - REL_VER: "master"
                - IMG_OUT: "u16phpall_dd_img"
                - RES_REPO: "u16phpall_dd_repo"
          script:
            - pushd $(shipctl get_resource_state "$RES_REPO")
            - REPO_COMMIT=$(shipctl get_resource_version_key "$RES_REPO" "shaData.commitSha")
            - export IMG_NAME=$(shipctl get_resource_version_key $IMG_OUT "sourceName")
            - export DH_USR_NAME=$(shipctl get_integration_resource_field $IMG_OUT "userName")
            - export DH_PASS=$(shipctl get_integration_resource_field $IMG_OUT "password")
            - sudo docker build -t=$IMG_NAME:$REL_VER --pull .
            - sudo docker login -u $DH_USR_NAME -p $DH_PASS
            - sudo docker push $IMG_NAME:$REL_VER
      - OUT: u16phpall_dd_img
    on_success:
      script:
        - shipctl put_resource_state_multi $JOB_NAME "versionName=$REL_VER" "IMG_REPO_COMMIT_SHA=$REPO_COMMIT"
        - shipctl put_resource_state_multi $IMG_OUT "versionName=$REL_VER" "IMG_REPO_COMMIT_SHA=$REPO_COMMIT" "BUILD_NUMBER=$BUILD_NUMBER"

  - name: u16cloall_x8664_build
    type: runSh
    triggerMode: parallel
    dependencyMode: strict
    steps:
      - IN: u16cloall_dd_repo
      - IN: u16all_dd_img
      - TASK:
          name: u16cloall_build
          runtime:
            options:
              env:
                - REL_VER: "master"
                - IMG_OUT: "u16cloall_dd_img"
                - RES_REPO: "u16cloall_dd_repo"
          script:
            - pushd $(shipctl get_resource_state "$RES_REPO")
            - REPO_COMMIT=$(shipctl get_resource_version_key "$RES_REPO" "shaData.commitSha")
            - export IMG_NAME=$(shipctl get_resource_version_key $IMG_OUT "sourceName")
            - export DH_USR_NAME=$(shipctl get_integration_resource_field $IMG_OUT "userName")
            - export DH_PASS=$(shipctl get_integration_resource_field $IMG_OUT "password")
            - sudo docker build -t=$IMG_NAME:$REL_VER --pull .
            - sudo docker login -u $DH_USR_NAME -p $DH_PASS
            - sudo docker push $IMG_NAME:$REL_VER
      - OUT: u16cloall_dd_img
    on_success:
      script:
        - shipctl put_resource_state_multi $JOB_NAME "versionName=$REL_VER" "IMG_REPO_COMMIT_SHA=$REPO_COMMIT"
        - shipctl put_resource_state_multi $IMG_OUT "versionName=$REL_VER" "IMG_REPO_COMMIT_SHA=$REPO_COMMIT" "BUILD_NUMBER=$BUILD_NUMBER"

  - name: u16ruball_x8664_build
    type: runSh
    triggerMode: parallel
    dependencyMode: strict
    steps:
      - IN: u16ruball_dd_repo
      - IN: u16all_dd_img
      - TASK:
          name: u16ruball_build
          runtime:
            options:
              env:
                - REL_VER: "master"
                - IMG_OUT: "u16ruball_dd_img"
                - RES_REPO: "u16ruball_dd_repo"
          script:
            - pushd $(shipctl get_resource_state "$RES_REPO")
            - REPO_COMMIT=$(shipctl get_resource_version_key "$RES_REPO" "shaData.commitSha")
            - export IMG_NAME=$(shipctl get_resource_version_key $IMG_OUT "sourceName")
            - export DH_USR_NAME=$(shipctl get_integration_resource_field $IMG_OUT "userName")
            - export DH_PASS=$(shipctl get_integration_resource_field $IMG_OUT "password")
            - sudo docker build -t=$IMG_NAME:$REL_VER --pull .
            - sudo docker login -u $DH_USR_NAME -p $DH_PASS
            - sudo docker push $IMG_NAME:$REL_VER
      - OUT: u16ruball_dd_img
    on_success:
      script:
        - shipctl put_resource_state_multi $JOB_NAME "versionName=$REL_VER" "IMG_REPO_COMMIT_SHA=$REPO_COMMIT"
        - shipctl put_resource_state_multi $IMG_OUT "versionName=$REL_VER" "IMG_REPO_COMMIT_SHA=$REPO_COMMIT" "BUILD_NUMBER=$BUILD_NUMBER"

  - name: u16scaall_x8664_build
    type: runSh
    triggerMode: parallel
    dependencyMode: strict
    steps:
      - IN: u16scaall_dd_repo
      - IN: u16javall_dd_img
      - TASK:
          name: u16scaall_build
          runtime:
            options:
              env:
                - REL_VER: "master"
                - IMG_OUT: "u16scaall_dd_img"
                - RES_REPO: "u16scaall_dd_repo"
          script:
            - pushd $(shipctl get_resource_state "$RES_REPO")
            - REPO_COMMIT=$(shipctl get_resource_version_key "$RES_REPO" "shaData.commitSha")
            - export IMG_NAME=$(shipctl get_resource_version_key $IMG_OUT "sourceName")
            - export DH_USR_NAME=$(shipctl get_integration_resource_field $IMG_OUT "userName")
            - export DH_PASS=$(shipctl get_integration_resource_field $IMG_OUT "password")
            - sudo docker build -t=$IMG_NAME:$REL_VER --pull .
            - sudo docker login -u $DH_USR_NAME -p $DH_PASS
            - sudo docker push $IMG_NAME:$REL_VER
      - OUT: u16scaall_dd_img
    on_success:
      script:
        - shipctl put_resource_state_multi $JOB_NAME "versionName=$REL_VER" "IMG_REPO_COMMIT_SHA=$REPO_COMMIT"
        - shipctl put_resource_state_multi $IMG_OUT "versionName=$REL_VER" "IMG_REPO_COMMIT_SHA=$REPO_COMMIT" "BUILD_NUMBER=$BUILD_NUMBER"
